{
 "title": "fd",
 "time": { "from": "2022-01-09T07:41:09.046Z", "to": "2022-01-09T07:48:14.853Z" },
 "panels": [
  {
   "title": "go_threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "go_threads{job=~\"server01|server02\"}"
    }
   ]
  },
  {
   "title": "go_goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "go_goroutines{job=~\"server01|server02\"}"
    }
   ]
  },
  {
   "title": "go_memstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~\"server01|server02\"}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~\"server01|server02\"}"
    }
   ]
  }
 ]
}